
package com.supinfo.suprails.web.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerOrderResource", targetNamespace = "http://soap.service.web.suprails.supinfo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerOrderResource {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://soap.service.web.suprails.supinfo.com/", className = "com.supinfo.suprails.web.service.soap.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://soap.service.web.suprails.supinfo.com/", className = "com.supinfo.suprails.web.service.soap.CreateResponse")
    @Action(input = "http://soap.service.web.suprails.supinfo.com/CustomerOrderResource/createRequest", output = "http://soap.service.web.suprails.supinfo.com/CustomerOrderResource/createResponse")
    public boolean create(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Long arg3);

}
