
package com.supinfo.suprails.web.service.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TripResource", targetNamespace = "http://soap.service.web.suprails.supinfo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TripResource {


    /**
     * 
     * @return
     *     returns java.util.List<com.supinfo.suprails.web.service.soap.Trip>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "all", targetNamespace = "http://soap.service.web.suprails.supinfo.com/", className = "com.supinfo.suprails.web.service.soap.All")
    @ResponseWrapper(localName = "allResponse", targetNamespace = "http://soap.service.web.suprails.supinfo.com/", className = "com.supinfo.suprails.web.service.soap.AllResponse")
    @Action(input = "http://soap.service.web.suprails.supinfo.com/TripResource/allRequest", output = "http://soap.service.web.suprails.supinfo.com/TripResource/allResponse")
    public List<Trip> all();

}
